In [4]:
import pandas as pd

In [5]:
w = pd.read_csv('C:/Users/Mac001/machine/wearther.csv',encoding='utf-8')

In [6]:
w

date  precipitation  temp_max  temp_min  wind  weather
0     2012-01-01            0.0      12.8       5.0   4.7  drizzle
1     2012-01-02           10.9      10.6       2.8   4.5     rain
2     2012-01-03            0.8      11.7       7.2   2.3     rain
3     2012-01-04           20.3      12.2       5.6   4.7     rain
4     2012-01-05            1.3       8.9       2.8   6.1     rain
...          ...            ...       ...       ...   ...      ...
1456  2015-12-27            8.6       4.4       1.7   2.9     rain
1457  2015-12-28            1.5       5.0       1.7   1.3     rain
1458  2015-12-29            0.0       7.2       0.6   2.6      fog
1459  2015-12-30            0.0       5.6      -1.0   3.4      sun
1460  2015-12-31            0.0       5.6      -2.1   3.5      sun

[1461 rows x 6 columns]

In [7]:
w_rm = w.rename(columns = {'precipitation':'강수량','temp_max':'최대온도','temp_min':'최소온도','wind':'바람'})

In [8]:
w_r = w_rm[['강수량','최대온도','최소온도','바람','weather']]

In [9]:
w_r

강수량  최대온도  최소온도   바람  weather
0      0.0  12.8   5.0  4.7  drizzle
1     10.9  10.6   2.8  4.5     rain
2      0.8  11.7   7.2  2.3     rain
3     20.3  12.2   5.6  4.7     rain
4      1.3   8.9   2.8  6.1     rain
...    ...   ...   ...  ...      ...
1456   8.6   4.4   1.7  2.9     rain
1457   1.5   5.0   1.7  1.3     rain
1458   0.0   7.2   0.6  2.6      fog
1459   0.0   5.6  -1.0  3.4      sun
1460   0.0   5.6  -2.1  3.5      sun

[1461 rows x 5 columns]

In [10]:
print(pd.unique(w_r['weather']))

['drizzle' 'rain' 'sun' 'snow' 'fog']


In [11]:
w_r_input = w_r[['강수량','최대온도','최소온도','바람']].to_numpy()

In [13]:
print(w_r_input[:10])
print()

[[ 0.  12.8  5.   4.7]
 [10.9 10.6  2.8  4.5]
 [ 0.8 11.7  7.2  2.3]
 [20.3 12.2  5.6  4.7]
 [ 1.3  8.9  2.8  6.1]
 [ 2.5  4.4  2.2  2.2]
 [ 0.   7.2  2.8  2.3]
 [ 0.  10.   2.8  2. ]
 [ 4.3  9.4  5.   3.4]
 [ 1.   6.1  0.6  3.4]]


In [15]:
w_r_target = w_r['weather'].to_numpy()

In [16]:
#### 데이터세트 만들기
from sklearn.model_selection import train_test_split
train_input, test_input, train_target, test_target = train_test_split(w_r_input,w_r_target,random_state=50)

In [17]:
from sklearn.preprocessing import StandardScaler
ss = StandardScaler()
ss.fit(train_input)
train_scaled = ss.transform(train_input)
test_scaled = ss.transform(test_input)

In [18]:
from sklearn.neighbors import KNeighborsClassifier
kn = KNeighborsClassifier(n_neighbors=3)
kn.fit(train_scaled, train_target)
print(kn.score(train_scaled,train_target))
print(kn.score(test_scaled,test_target))

0.8347031963470319
0.7158469945355191


C:\Users\Mac001\anaconda3\lib\site-packages\sklearn\neighbors\_classification.py:228: FutureWarning: Unlike other reduction functions (e.g. `skew`, `kurtosis`), the default behavior of `mode` typically preserves the axis it acts along. In SciPy 1.11.0, this behavior will change: the default value of `keepdims` will become False, the `axis` over which the statistic is taken will be eliminated, and the value None will no longer be accepted. Set `keepdims` to True or False to avoid this warning.
  mode, _ = stats.mode(_y[neigh_ind, k], axis=1)
C:\Users\Mac001\anaconda3\lib\site-packages\sklearn\neighbors\_classification.py:228: FutureWarning: Unlike other reduction functions (e.g. `skew`, `kurtosis`), the default behavior of `mode` typically preserves the axis it acts along. In SciPy 1.11.0, this behavior will change: the default value of `keepdims` will become False, the `axis` over which the statistic is taken will be eliminated, and the value None will no longer be accepted. Set `keepd

In [19]:
print(kn.classes_)

['drizzle' 'fog' 'rain' 'snow' 'sun']


In [20]:
print(kn.predict(test_scaled[:5]))

['rain' 'sun' 'sun' 'rain' 'rain']


C:\Users\Mac001\anaconda3\lib\site-packages\sklearn\neighbors\_classification.py:228: FutureWarning: Unlike other reduction functions (e.g. `skew`, `kurtosis`), the default behavior of `mode` typically preserves the axis it acts along. In SciPy 1.11.0, this behavior will change: the default value of `keepdims` will become False, the `axis` over which the statistic is taken will be eliminated, and the value None will no longer be accepted. Set `keepdims` to True or False to avoid this warning.
  mode, _ = stats.mode(_y[neigh_ind, k], axis=1)


In [27]:
import numpy as np
proba = kn.predict_proba(test_scaled[:5])
#predict_proba() = 예측 확률 반환
print(test_scaled)
print('*'*50)
print(np.round(proba,decimals=3))

[[-0.08586479 -0.3979399  -0.17126834 -0.09018417]
 [-0.37895066 -0.54586404 -0.72256361 -0.5752801 ]
 [-0.45222212  0.65097676  1.36448276  0.60281001]
 ...
 [-0.45222212  1.0947492   0.93132219  1.43440303]
 [-0.45222212  1.25612099  1.14790248  0.11771408]
 [-0.45222212  1.92850347  1.24634806  0.1870135 ]]
**************************************************
[[0.    0.    1.    0.    0.   ]
 [0.333 0.    0.    0.    0.667]
 [0.    0.    0.333 0.    0.667]
 [0.    0.    0.667 0.    0.333]
 [0.    0.333 0.667 0.    0.   ]]


In [52]:
distances, indexes = kn.kneighbors(test_scaled[3:4])
print(train_target[indexes])

[['rain' 'rain' 'rain']]


In [28]:
#로지스틱 회귀 다중분류  예측 정확도
from sklearn.linear_model import LogisticRegression
lr = LogisticRegression()
lr.fit(train_scaled, train_target)
print(lr.score(train_scaled,train_target))
print(lr.score(test_scaled,test_target))

0.7917808219178082
0.7786885245901639


In [29]:
#처음 테스트 세트 5개 샘플 예측
print(lr.predict(test_scaled[:5]))

['rain' 'sun' 'sun' 'rain' 'rain']


In [38]:
#예측확률
proba = lr.predict_proba(test_scaled[:5])
#predict_proba() = 예측 확률 반환
print(np.round(proba,decimals=2))

[[0.02 0.03 0.91 0.   0.04]
 [0.08 0.13 0.31 0.   0.48]
 [0.02 0.05 0.42 0.   0.51]
 [0.04 0.05 0.63 0.02 0.26]
 [0.   0.01 0.98 0.   0.  ]]


In [31]:
print(lr.classes_)

['drizzle' 'fog' 'rain' 'snow' 'sun']


In [32]:
print(lr.coef_.shape, lr.intercept_.shape)
#배열의 열 4개 행 5개
#소프트 맥스 함수를 사용하여 5개의 z개의 값을 확률로 변환

(5, 4) (5,)


In [33]:
#소프트 맥스 함수 사용
decision =lr.decision_function(test_scaled[:5])
#decision_function() = 모델이 학습한 선형 방정식의 출력을 반환
print(np.round(decision, decimals=2))

[[-0.8  -0.35  3.21 -2.1   0.04]
 [-0.16  0.35  1.21 -3.06  1.66]
 [-0.33  0.73  2.8  -6.2   3.  ]
 [-0.84 -0.51  1.93 -1.61  1.04]
 [-0.26  0.72  5.24 -5.18 -0.52]]


In [36]:
from scipy.special import softmax
proba = softmax(decision, axis=1)
print(np.round(proba,decimals=0))
#이슬비,안개,비,눈,태양

[[0. 0. 1. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 1.]
 [0. 0. 1. 0. 0.]
 [0. 0. 1. 0. 0.]]


#### 로지스틱 회귀
    -선형 방정식 분류 알고리즘, 선형 회귀와 달리 시그모이드, 소프트맥스 함수를 사용하여 확률을 출력
#### 다중분류
    -클래스가 2개 이상인 분류 문제, 로지스틱은 다중 분류를 위해 소프트맨스 함수를 사용하여 클래스 예측
#### 시그모이드 함수
    - 선형 방정식 출력을 0~1 값으로 압축 이진분류를 위해 사용
#### 소프트맥스 함수
    - 다중분류에서 선형방정식 출력 결과를 정규화 하여 합이 1이 되도록 만듬
    